name: TG File Stream Bot

services:
  fsb-run:
    image: ghcr.io/everythingsuckz/fsb
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./fsb.env:/app/fsb.env
    env_file:
      - path: ./fsb.env
        required: true
